### PR TITLE
Added content from 2018 website

### PR DESCRIPTION
**Pull request by EmmanuelCobian**
Added content from 2018 website, specifically, the tables for the schedule and workshop sections. Also changed some of the text. I changed "racially diverse" to "diverse" and "ideation" to "brainstorm".

### CODE REVIEW

**Review by smartspot2 — CHANGES_REQUESTED** [review]
Since you've taken the initiative and also copied the schedule from last year, you should probably also clean up the layout of the schedule/workshops (too much padding/margin below the tables. (If you also want to take #6 you can as well, since you're already doing work on the schedule)

Also, could you merge the workshop schedule with the overall schedule? We'll probably edit the design of the schedule later on, and every item is going to be consolidated in one navigable menu.

If you merge the two schedules, you can also change the background colors back to the original colors, since we're removing a section that way.

Thank you for your hard work!

**Review by smartspot2 — COMMENTED** [review]
Ah, sorry if I was unclear in the last comment, but I wanted the workshop events to be mixed in with the other schedule events, instead of having an entirely different table for the workshop stuff. (@Zephyril any input on this?)

Also, now that I've looked at the schedule section more, it seems a bit too long; maybe put the two tables side by side instead? With the Saturday schedule on the left and the Sunday schedule on the right?

**Comment by EmmanuelCobian** [comment]
> Ah, sorry if I was unclear in the last comment, but I wanted the workshop events to be mixed in with the other schedule events, instead of having an entirely different table for the workshop stuff. (@Zephyril any input on this?)
> 
> Also, now that I've looked at the schedule section more, it seems a bit too long; maybe put the two tables side by side instead? With the Saturday schedule on the left and the Sunday schedule on the right?

Ok, I'll work on that

Thanks for the feedback

**Comment by jsn-li** [comment]
> Ah, sorry if I was unclear in the last comment, but I wanted the workshop events to be mixed in with the other schedule events, instead of having an entirely different table for the workshop stuff. (@Zephyril any input on this?)
> 
> Also, now that I've looked at the schedule section more, it seems a bit too long; maybe put the two tables side by side instead? With the Saturday schedule on the left and the Sunday schedule on the right?

Definitely put them into one schedule this time.

**Comment by smartspot2** [comment]
This looks really good—great work! The only thing that is bothering me right now is that the button's color makes it stand out a bit too much. A grey/black color would probably be better, though it's completely up to your discretion on this; feel free to leave it as is if you feel like it's okay.

The text shadow on hover is a bit too strong and makes it look a bit weird. Removing the text shadow and leaving the background color change on hover is probably better.

Again, thank you for your hard work so far!

**Comment by alexnovo52** [comment]
Wow! Good work! My only issue is that the left information box is not in line with the right date. It seems to be above the date. Also there seems to be a lot of empty space on the left. Perhaps a detail box with more information on the event?

**Review by smartspot2 — APPROVED** [review]
Looks great! As always, thank you for your hard work in implementing an entirely new design for the schedule. For now, I think it'll do, since we haven't finalized the schedule events yet—as we get closer to the event, we may change up some parts of the schedule to make it fit better with the content.

We'll use your current design for the schedule. though we may hide it for the current production stage, since the events are still from last year. I'm just going to make a few small clean-ups with your code and improve clarity in some things, but other than that, it looks good!

**Pull request merged**
